### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by victorkl400** [tomek-o/tSIP#13]
Could you explain , how do i run it using the source code? i do have c++ builder 6/visual studio 2019/borland c++.
It would be great to figure out how does it run.
Thx

**Comment by tomek-o** [comment]
With Turbo C++/BDS2006 I'm just opening project group, selecting either Debug or Release target and rebuilding.
Visual C++ is a very different product. To use it most of the GUI would need to be rewritten. Perhaps starting with baresip might make more sense for VC++ as there are at least project files.
C++ Builder 6 is very similar to BDS2006, although project files are not compatible, so they would need to be recreated.
I'm not sure what do you mean by "Borland C++" (third product on the list).

**Comment by victorkl400** [comment]
Borland C++ 5.02 (https://techrrival.com/download-borland-turbo-c-windows/) is that the Turbo C++/BDS2006 ? 
I've never heard about any of borland or turbo c++ before so I'm really confused .
I'm struggling for days to figure out how to run your code .
Could you provide me a link to download this " Turbo C++/BDS2006"?

**Comment by tomek-o** [comment]
BC++ 5 is another, older product from the times when DOS, Win 3.11 and maybe Win95 were in use, not much in common except "Turbo" name.
Turbo C++ Explorer was withdrawn few years ago. It is very likely that as free software with liberal license it was competing with paid versions of C++ Builder. It is not available anymore, but required are indexed by google and seem to be still available on few sites. These files are:

- prereqs_en.zip - .net 1.1 and few others required dependencies
- turbocpp_en.exe or turbocpp_en.iso.zip
- reg740.txt - license
- probably not critical, but highly recommended: BDS2006HotFixRollup2.exe, BDS2006Upd2_Hotfix11.zip, BDS2006Upd2_HF12.zip, BDS2006Upd2_HF13.zip

On Windows 7 BDS2006 has some issue with "EditorLineEnds" file, so there is run_bds.bat and run_bds_x64.bat. On Windows 10 x64 it seems to be fine.

**Comment by victorkl400** [comment]
I think I´ve got the right bds2006.
But now i cannot compile/build :/ 
![image](https://user-images.githubusercontent.com/30088769/84962597-98709f00-b0dd-11ea-9b9a-2e9b10239ffe.png)

Btw sorry for bother you that much.

**Comment by tomek-o** [comment]
This is almost the same to what I'm using, but for some reason standard include paths are missing or they are named in different way.
In my installation there is BDS system variable pointing to c:\program files (x86)\borland\bds\4.0 and standard headers are e.g. in C:\Program Files (x86)\Borland\BDS\4.0\include ($(BDS)\include, $(BDS)\include\dinkumware, $(BDS)\include\vcl).
This variable is visible in Tools/Options/Environment Variables.
It might be different in "full" BDS or your installation might not work / be incomplete. Maybe C++ support is opt-in installation option in full BDS?

Try creating basic VCL or command line "Hello world", including e.g. stdlib.h in source and see if it works. If it works but there is no BDS variable visible - check if there is any similar variable, you can also add extra variables there.

**Comment by victorkl400** [comment]
Seems working like charm.

![image](https://user-images.githubusercontent.com/30088769/85041526-6c4a3200-b160-11ea-9ba4-ae62c4bf66d5.png)

I dont know why your code isnt compiling/building at all

**Comment by tomek-o** [comment]
If installation is fine then this might be some issue with paths, though it is pretty weird that Turbo C++ Explorer and full BDS define them in different way.
In my projects (generated by TC++) include paths are defined as this:

```
$(BDS)\include
$(BDS)\include\dinkumware
$(BDS)\include\vcl
```
(there are also linker and debugger paths, but let's start with includes).
And BDS variable is defined by IDE:
![BDS](https://user-images.githubusercontent.com/43222462/85049611-2fe4f900-b195-11ea-866d-75b0a245e457.png)
Check if your IDE defines BDS variable or is it named in some other way or maybe some subfolder is used for installation that can potentially have both Delphi and C++. Can you attach your project file for comparison?

**Comment by victorkl400** [comment]
BDS2006 Enviroment Variables (looks same as yours)

![image](https://user-images.githubusercontent.com/30088769/85051424-dd441680-b16d-11ea-9e15-8acbac8a27d6.png)

And i do have types.h in borland include file also 
![image](https://user-images.githubusercontent.com/30088769/85052093-c05c1300-b16e-11ea-847e-1da6ebc0ead0.png)

**Comment by tomek-o** [comment]
One more guess - maybe same options are named in different way in project files. Do you see include paths in project properties?
![BDS2](https://user-images.githubusercontent.com/43222462/85054051-c0263c80-b19b-11ea-89d5-fb2ab99a4ebd.png)
Can you attach your (working) project file for comparison?

**Comment by victorkl400** [comment]
![image](https://user-images.githubusercontent.com/30088769/85054659-c653f300-b172-11ea-969e-bc6f40e9ca8b.png)

**Comment by tomek-o** [comment]
I'm out of ideas. Working and non-working project would need to be compared manually.

**Comment by victorkl400** [comment]
Alright , I'll keep trying to figure out what is going wrong. 
Anyway , thanks for help and for your awesome project.

**Comment by tomek-o** [comment]
I don't want to install BDS2006 on my PC (it probably would collide with TC++), can you attach your working "Hello world" project (at least .bdsproj file or whole project zipped)?

**Comment by victorkl400** [comment]
Sure , give me a sec.

**Comment by victorkl400** [comment]
[test.zip](https://github.com/tomek-o/tSIP/files/4800480/test.zip)

**Comment by tomek-o** [comment]
I don't see anything overly suspicious and it compiles here. I'm attaching also my basic project for comparison.
[turbo.zip](https://github.com/tomek-o/tSIP/files/4800539/turbo.zip)
Assuming that application projects are compatible, maybe this problem is specific to static library projects (as re.bdsproj is this type of project)? Base/empty static library project from my TC++: 
[turbo_static_lib.zip](https://github.com/tomek-o/tSIP/files/4800571/turbo_static_lib.zip)

**Comment by victorkl400** [comment]
Your basic project is working here so far as well.

**Comment by tomek-o** [comment]
Another thing that might be worth checking - is this problem specific to re.bdsproj or not? There is e.g. \rem\mk\win32-tc\rem.bdsproj and any library can be opened and compiled separately.

One suspicious project option in re.bdsproj is inclusion of (missing but not actually necessary - it was added automatically and I forgot about it) of ..\_PROJEKTY\libre\re-0.3.0\mk\win32-tc path. This can be removed from bdsproj file either manually (text editor) or through project options, Paths and Defines, Build Configuration: All configurations (greyed position on list). Maybe for unknown reason this causes BDS (but not TC++) to ignore following include paths.
![BDS3](https://user-images.githubusercontent.com/43222462/85063354-506b7e00-b1aa-11ea-9d99-eb57b83f7002.png)

**Comment by victorkl400** [comment]
As you said , I removed PROJEKTY , tried compile still the same.
![image](https://user-images.githubusercontent.com/30088769/85064461-f951b300-b181-11ea-9cb7-00d66fccada5.png)

**Comment by victorkl400** [comment]
If i get the Turbo C++ would it work , wouldn't it ? Do you have any installer or files that i could try to run it on my computer ?

**Comment by tomek-o** [comment]
I believe there shouldn't be a problem - today someone asked me same question and I pointed to https://github.com/tomek-o/tSIP/issues/13#issuecomment-645576697 and first google link: http://194.71.11.165/mirror/archive/ftp.sunet.se/pub/lang/borland/ - seemed to work in less than a hour, but I actually did not ask if compiling finished.
... but I also don't think there should be any problem with BDS2006, it should be virtually identical except for branding, Delphi support and few patches maybe.

**Comment by victorkl400** [comment]
So , don't you have any other idea to help me ? If you don't mind i can give you remote access to my computer.
It'd be great getting this working.

**Comment by tomek-o** [comment]
To be sure if there are no problems with these install files I've just asked one guy that used these links today, there might be time zone difference though.
In general I would recommend TC++.
At the moment it's getting late here, so I would prefer not to start remote desktop session, but if you won't find solution I should have time tomorrow after 19:00 CET/GMT+2 or on Saturday. I guess option that left might be recreating project file and adding source files manually, checking if/when it breaks. Not difficult (re.bdsproj has one or two essential options to change - adding HAVE_SELECT define, changing linker page size to 128, maybe setting data alignment), but potentially time consuming (iterative).

**Comment by victorkl400** [comment]
Okay , so i will take a look at turbo c++ , try to install it

**Comment by victorkl400** [comment]
Well , I tried to run Turbo C++ but no success , still up to access here remotely ?

**Comment by tomek-o** [comment]
Yup, I can try. Please use e-mail from my webpage for details (not sure if github has private messages).

**Comment by tomek-o** [comment]
So, here are my notes after building tSIP with this version of BDS2006. Perhaps it was unpatched as it was crappier than Turbo C++ Explorer and this is saying a lot.

1. Issue with no access to standard includes seemed like a problem with limited command line length. I don't know exactly whether this is Windows or IDE problem, I've seen this first time and absolute paths were not longer than typical. As IDE is inserting include paths automatically for each source subfolder (at least I don't know workaround for this) I've moved part of re.lib code from subfolders to common folder, reducing total length/number of include paths. 

2. ws2tcpip.h apparently needs fixing (missing __BORLANDC__ condition), changing to:

```
#if defined(_MSC_VER) || defined(__BORLANDC__)
#define WS2TCPIP_INLINE __inline
#else
#define WS2TCPIP_INLINE extern inline /* GNU style */
#endif
```

3. There was ambiguity error with strcmp function in jsoncpp.lib. I'll test it with TC++ and probably change.
4. There was minor issue with precompiled header, "E2209 Unable to open include file 'ChartFX.hpp'": https://support.embarcadero.com/article/35876
5. Not exacly an issue, but build configuration selection is different than in TC++ and I think it might require manually activating each project and changing its configuration. I've compiled only "Release" targets there. If both Release and Debug would be compiled then it might be less of a problem as often only single "tSIP_exe.bdsgroup" would need to be opened (if not touching libraries).
6. For baresip.lib project obj files were generated in incorrect folder - not in Release_Build but one level higher. Generated library was empty, with size = 1024B only. I had to manually copy obj files to Release_Build and rebuild library project to link them. Beware, this might cause lot of confusion when changing code.
7. Executable was not able to run without winspool.dll (and it normally is self-contained!). Following https://www.cyberforum.ru/cpp-builder/thread89061.html I've copied winspool.drv from System32 to Release_Build directory and renamed it to winspool.dll. This thread says that it might be fixed with BDS2006 updates.
