### ISSUE TITLE
Fantastic Software: Request for Minor Feature

### ISSUE THREAD

**Issue by AsokAsus** [tomek-o/tSIP#2]
Your tSIP.exe program is truly awesome!

And I'm using it as the softphone for my own website: myvoipmsalt.com, which is itself my own GUI based on the API of the voip.ms service.

tSIP.exe is so awesome, i'd like to use it as the default with the broswer sip: protocol, so i could use the standard "sip:" protocol name in my web codes.

however, when i attempt to use "sip" in the tsip.exe program's browser integration configuration option, the browsers all insist on using "sip:nnnnnnnn" as the value for "%1", with the browser-generated command looking like:

[path]/tSIP.exe /tsip="sip:nnnnnnnn"

However, tSIP.exe accepts only /tsip="tsip:nnnnnnnn"

It would be really nice if tSIP.exe accepted /tsip="sip:nnnnnnnn" as well as /tsip="tsip:nnnnnnnn"

**Comment by tomek-o** [comment]
Thanks!
I think this problem is caused by "sip:" prefix being processed in special way by tSIP (intended to be used for direct IP calls, same as from regular dial edit).
I've added extra option in "Integration" tab to disable this [(commit link)](https://github.com/tomek-o/tSIP/commit/8e34fc531d0ef34543adcafae9be610503fb0b21). Updated executable (0.1.67.03) is at [http://tomeko.net/tmp/tSIP.exe](http://tomeko.net/tmp/tSIP.exe).
