### ISSUE TITLE
Custom sound buttons

### ISSUE THREAD

**Issue by npstn-soft** [tomek-o/tSIP#23]
It would be cool if there was a feature to add configurable buttons to the UI that play a sound file to the caller you are connected to.

**Comment by tomek-o** [comment]
There is quite old, probably suboptimal (requiring wave files with extra second of silence at the end) but still working example at https://tomeko.net/software/SIPclient/howto/playing_audio_during_call.php.
One important thing is that wave files no longer need to match call audio sampling frequency (there is resampler).
For additional visual indication (there is only "Beep" in the script above) of playing I guess SetButtonCaption, SetButtonDown or SetButtonImage could be used.

**Comment by InterLinked1** [comment]
Personally, I think the ability to send a custom tone would be more useful than a sound file.
For instance, in addition to "DTMF" as a custom dropdown button, "Tone" could be an option, and instead of the DTMF digit, you enter the frequency, e.g. 1004 or 2600 or 1700+2200, and then pressing that button will play that tone as long as it is held down. Would actually be very dead useful for lots of testing and other things that I can think of.

**Comment by tomek-o** [comment]
> ability to send a custom tone

Only shortly tested with spectrum analyzer (I actually don't have PABX with acoustic tone detector at hand for "real" tests), but here is new Lua GenerateTones() function description: https://tomeko.net/software/SIPclient/howto/generate_tones.php.
It requires latest executable (http://tomeko.net/tmp/tSIP.exe).

This can generate up to 4 sine waves at once, with selected amplitudes and frequencies.

There are actually few ways to use wave files for similar purpose (Lua: SwitchAudioSource(), separate button type for same function), though one issue with wave files (switching between audio devices in general) is occasional audible audio disturbance for a fraction of a second when switching. Not a big problem for voice announcements in my opinion, but possibly interfering with tone detectors if switching would be very frequent as I might expect from momentary buttons.
