### ISSUE TITLE
ctrl_tcp modules

### ISSUE THREAD

**Issue by Bettman66** [tomek-o/tSIP#31]
Hello Tomasz,
would it be possible to integrate the ctrl_tcp module from Baresip.
I have programmed a full screen browser for home automation in Delphi and would like to use your program to communicate with a door intercom. The command line commands work well, but I also need the sip actions such as call, hang up, etc.
With a TCP socket module, your program would be controllable from any programming language.

**Comment by tomek-o** [comment]
I would have to think about it. Using ctrl_tcp "as is" might not work as I'm not using baresip-like commands at the moment, but maybe short scripts could be used alternatively (scripting is already present, maintained and most likely more powerful than commands).

If you would need only commands (not feedback and events) then scripts can be already passed to application using "SCRIPT" argument for short scripts (https://tomeko.net/software/SIPclient/howto/command_script_and_call_queue.php), "SCRIPT_B64" for scripts encoded with base64 (it turns out that escaping scripts to be passed by command line is quite confusing) or "SCRIPT_FILE". Technically files (written from Lua) could be used for feedback, it is not elegant though.

Few very basic commands are also available aside from scripting (but scripting would be way more powerful):
```
tSIP.exe /tsip=123456789 (dialing)
tSIP.exe /tsip=HANGUP (disconnecting current call)
tSIP.exe /tsip=ANSWER (answering incoming call)
tSIP.exe /tsip=APP_QUIT (closing running softphone)
tSIP.exe /tsip=SHOWWINDOW (bringing window to the front)
tSIP.exe /tsip=PROGRAMMABLE_BTN_xxx (simulating programmable button being pressed, xxx = button ID, 0...100+)
```
There is TCP client plugin (https://tomeko.net/software/SIPclient/TcpClient/) that can be used for similar purposes, I'm not sure if its documentation is sufficient though. Scripts can pass text commands to this plugin and commands received by the plugin are pushed to queue than can be polled e.g. inside "on timer" script. Maybe similar "TcpServer" plugin could also be viable.

Depending on what part of GUI you need/want reimplement, using baresip directly (e.g. wrapping it as some dll) might be also an option, especially if you would need mostly calling and environment is somehow controlled (end user does not need to change settings).

**Comment by Bettman66** [comment]
Yes a TCP server plugin would be great and easy to do. I use this in NodeJS for data exchange between my programs and the SmartHome.
If an action is recognized (call, hangup, DTMF), the message is sent to all TCP clients. The client can also send an action to the server (call *610, accept, hangup, dtmfsend #0815).
Please take a look, it's not difficult. ;-)

**Comment by tomek-o** [comment]
TCP server instruction is now at https://tomeko.net/software/SIPclient/TcpServer/.
I do not have real use for this at the moment, it is only shortly tested.

**Comment by Bettman66** [comment]
Thank you very much,
I will test the plugin and let you know.

**Comment by Bettman66** [comment]
The TCP server plugin works great with external programs.
Thanks again Tomasz.
