### ISSUE TITLE
Lua command GetRecorderState() return nil

### ISSUE THREAD

**Issue by hillxrem** [tomek-o/tSIP#46]
Both in version 0.3 and 0.3.03, Lua command GetRecordingState() works correctly, but GetRecorderState() always seems to return nil, whether it takes a Call uid as an argument or not. Also, I am not sure if this is related, but the "on recorder state" event in "Scripts" in Settings also does not seem to work correctly whether the recorder is started or stopped.

My goal is to get the scripts listed at 
https://tomeko.net/software/SIPclient/howto/record_pause_resume.php 
working correctly.

**Comment by tomek-o** [comment]
Thanks, it is fixed now in https://tomeko.net/tmp/tSIP.exe (this executable version is without video support).

SetButtonImage/SetButtonDown might be used to make state more readable.

Since version 0.3 each call/line has separate recorder, so if multiple call feature is used then I guess recording state and controls might need to be assigned to each line, maybe grouped visually with LINE buttons. I don't have an example for this though at the moment.

**Comment by hillxrem** [comment]
Thank you very much for your prompt response. It works as expected. Also, thank you for the idea to make the buttons easier to read.

It would be great if you could incorporate this fix into future updates.

**Comment by tomek-o** [comment]
> It would be great if you could incorporate this fix into future updates.

It definitely should be included, but in general I want to have at least half a dozen bulletpoints in changelog and/or few weeks timespan between releases - that's why I'm often pointing to single exe for a quick/minor updates.
