### ISSUE TITLE
Open project in RAD C++ 10.3 Community Edition

### ISSUE THREAD

**Issue by Winsor** [tomek-o/tSIP#7]
As far as I understand, the project file format has changed in new versions. therefore
\<Option Name = "Personality"> CPlusPlusBuilder.Personality </Option\>
not supported and any projects fails on opened.
Is there any way to open your projects in the current version? 
Perhaps I forgot to install any required software?

**Comment by tomek-o** [comment]
From my test with 10.3.2 (installed in November 2019) importing/opening project doesn't work. There are some claims (https://community.idera.com/developer-tools/general-development/f/rad-studio-general/68487/import-of-bds2006-project-fails/91185#91185) that it worked in 10.2, although I have doubts as it didn't work for me back in 2016 with 10.1 (https://forums.embarcadero.com/thread.jspa?threadID=228798).

I do have 10.3.2 installed at the moment and I was porting small project (due to Unicode being required) to it from Turbo C++/BDS2006 in November. I had to create new project and move files manually. There are minor modifications required like changing #include <FileCtrl.hpp> to #include <Vcl.FileCtrl.hpp>, adding few extra VCL headers, changing SelectDirectory function calls - nothing serious, mostly guesswork based on compiler and linker errors. It probably might be more complex and/or time consuming with medium size project (tSIP with all dependencies).

I'm not too eager with moving to 10.x C++ Builder Community myself as its license is quite restrictive (IMO much worse than "Turbo" series or even Delphi 2005 Personal) and I can't even be sure if I would be able to use it next year (it is licensed for one year, had to be reinstalled after this and it web install only).

**Comment by Winsor** [comment]
Thanks for the detailed explanation!
